### ISSUE TITLE
inline CSS 제거

### ISSUE THREAD

**Issue by yeojin-dev** [peimehen/sparta#1]
https://github.com/peimehen/sparta/blob/7791bab162b3a7814a48d551dee3a5f579515151/%EA%B3%BC%EC%A0%9C(2019.01.09)_%EC%99%84%EC%84%B1.html#L71
웹사이트 규모가 커지면 커질수록 inline CSS는 코드를 읽기 어렵게 만들고 수정을 번거롭게 합니다. 불편해도 클래스로 처리하는 것이 효과적입니다.

**Comment by peimehen** [comment]
넵  감사합니다 ^^
