### ISSUE TITLE
2주차 과제에서 빈칸 입력 가능

### ISSUE THREAD

**Issue by yeojin-dev** [peimehen/sparta#2]
![Screen Shot 2020-01-27 at 22 57 48](https://user-images.githubusercontent.com/38222260/73180425-a6d31400-4158-11ea-8c07-3880eaddbf15.png)
위와 같이 주문자 이름, 주소에서 빈칸으로 주문하기가 가능합니다.

**Comment by peimehen** [comment]
오류수정하였습니다.
